import Head from "next/head";
import Image from "next/image";
import formImage from "../public/form.png";
import { useFormik } from "formik";
import * as Yup from "yup";

export default function Home() {
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "Estonia",
      terms: false,
    },
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less")
        .required("Name is required"),
      terms: Yup.boolean().isTrue("Terms of service must be checked"),
    }),
    onSubmit: (values) => {
      console.log("form submitted");
      console.log(values);
    },
  });

  console.log(formik.errors);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="h-screen items-center flex justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white md:flex md:rounded-lg font-latoRegular"
        >
          <div className="flex-1 text-gray-700  p-20">
            <h1 className="text-3xl pb-2 font-latoBold">
              Let's get started 👋
            </h1>
            <p className="text-lg text-gray-500">
              Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.
            </p>
            <div className="mt-6">
              <div className="pb-4">
                <label
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-500"
                      : ""
                  } `}
                  htmlFor="name"
                >
                  Name
                </label>
                <input
                  type="text"
                  name="name"
                  placeholder="Enter your name here"
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-pink-400 focus:ring-pink-400"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4">
                <label className="font-latoBold block pb-2" htmlFor="email">
                  Email
                </label>
                <input
                  type="email"
                  name="email"
                  placeholder="Enter your email here"
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-pink-400 focus:ring-pink-400"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                />
              </div>
              <div className="pb-4">
                <label className="font-latoBold block pb-2" htmlFor="country">
                  Country
                </label>
                <select
                  name="country"
                  className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-pink-400 focus:ring-pink-400"
                  value={formik.values.country}
                  onChange={formik.handleChange}
                >
                  <option>Estonia</option>
                  <option>Spain</option>
                  <option>Brazil</option>
                  <option>Moldova</option>
                </select>
              </div>
              <div className="pb-4">
                <label className="font-latoBold block pb-2" htmlFor="terms">
                  Terms of service
                </label>

                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    name="terms"
                    className="h-5 w-5 text-pink-400 border-2 rounded-sm focus:border-pink-400 focus:ring-pink-400"
                    value={formik.values.terms}
                    onChange={formik.handleChange}
                  />
                  <p className="text-sm font-latoBold text-gray-500">
                    I agree to the Terms and Service that my data will be taken
                    and sold.
                  </p>
                </div>
              </div>
              <button
                type="submit"
                className="bg-pink-400 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                Start learning today!
              </button>
            </div>
          </div>
          <div className="relative hidden md:flex flex-1">
            <Image
              className=" object-cover rounded-lg"
              fill
              priority
              src={formImage}
              alt="form-learn"
            />
          </div>
        </form>
      </main>
    </>
  );
}



